### ISSUE TITLE
Is it support test at debug mode

### ISSUE THREAD

**Issue by ducan-ne** [linux-china/vitest-jetbrains-plugin#1]
I have not tested this plugin at all but want ask you first, is it can run at debug mode or any plan to do it rn?, if so, the plugin so desirable

**Comment by linux-china** [comment]
This plugin just a  temp solution  before official Vitest  support from WebStorm.  I think JetBrains people will do this job and they know Viest is great. :)    https://youtrack.jetbrains.com/issue/WEB-54437    No plan for debug now.
