### ISSUE TITLE
read `vitest.config` for monorepos

### ISSUE THREAD

**Issue by meoyawn** [linux-china/vitest-jetbrains-plugin#10]
Hi, thank you so much for this

I am reading `.env.test` files in my tests like this in `vitest.config.ts`:

```ts
import { defineConfig, loadEnv } from "vite"

// noinspection JSUnusedGlobalSymbols
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "")
  Object.assign(process.env, env)
  return {}
})
```

but my env vars are not loaded when running `vitest` with this plugin

Any help appreciated

**Comment by linux-china** [comment]
@meoyawn  you means global configuration support like following?

```typescript
export default defineConfig({
	plugins: [vue()],
	test: {
		environment: 'jsdom',
		globals: true,
	},
})
```

If you want to enable vitest globals enabled, please add comment line `// test: { globals: true} ` as following: 
 

```typescript
import { defineConfig, loadEnv } from "vite"

// noinspection JSUnusedGlobalSymbols
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "")
  Object.assign(process.env, env)
  // test: { globals: true} 
  return {}
})
```

**Comment by meoyawn** [comment]
@linux-china thanks for responding

I run tests with `vitest run src/`, it loads `vitest.config.ts` (with `loadEnv`) then runs everything

**Comment by meoyawn** [comment]
@linux-china oh, I just realized the problem was my monorepo. I have several subpackages in a monorepo: `front`, `back`, `shared`

config not loaded:
`back/vitest.config.ts`
`back/src/__tests__/demo.test.ts`

only `back` needs to load `.env.test`, so I specified it in root `vitest.config.ts`

```ts
import { defineConfig, loadEnv } from "vite"
import { join } from "path"

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, join(process.cwd(), "back"), "")
  Object.assign(process.env, env)
  return {}
})
```

alright, my issue is solved. Thanks again
