### ISSUE TITLE
gutter icons only on js and jsx files

### ISSUE THREAD

**Issue by Kaiser-Nico** [linux-china/vitest-jetbrains-plugin#13]
Hello, for some reason the icons to start the tests are only displayed in .js and .jsx files. My setup looks like this:

vite.config.js:
`test: {
    globals: true,
  },`

tsconfig.json:
`"compilerOptions": {
"types": [ "vitest/globals"]
},
"include": [
    "src",
    "node_modules/vitest/globals.d.ts"
  ]
`

**Comment by linux-china** [comment]
@Kaiser-Nico could share your demo example on GitHub?  and I will take a look.  Thanks.

**Comment by timges** [comment]
I can second @Kaiser-Nico. Gutter Icons only appear on *.test.js(x) files.

**Comment by linux-china** [comment]
Vitest Runner plugin does not check the file name pattern, and just check method call of "test", "it", "describe" from Vitest.

![image](https://user-images.githubusercontent.com/46711/177427960-14b039eb-db1a-40ac-9c9a-4ea988839c25.png)


Any screenshot or example repo?

**Comment by nika-d** [comment]
Hi! 
I had the same problem, and your last answer, linux-china, helped me to fix it, thank you very much! 

In my project, we switched from jest to vitest. 

Now, jest is removed from the devDependencies. Anyway, during npm install for example @types/jest is installed (resolved as co dependency or something). And going in the editor from the "describe" method call to its definition leads still to @types/jest . So PhpStorm is really convinced, that i want to use jests descibe, not that of vitest. 

A working fix is to add `import {descibe} from 'vitest'` in the test file . 

Thats how i do it now. Unfortunately, i have to put it in every test file again and again. Would be sensful to tell PhpStorm that its by default the vitest-describe. Any hint how to do that would be appreciated. :)

**Comment by linux-china** [comment]
@nika-d  could you share the simple project on github?  and I could take a look.

**Comment by nika-d** [comment]
Hi @linux-china ! 

Thanks a lot for your quick reply, and sorry for the late answer. I had to coordinate with colleagues to publish the code here. 

Please find the repo here: https://github.com/nika-d/LLP-Frontend

Additionally, here is my `.idea`-Folder : [idea.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/9148774/idea.zip)
Maybe the issue is connected to workspace or something...? 

The suggested fix with postinstall is a good idea! Thanks for that, too 🙂

And if you dont have time for further investigation here - its totally fine! I mean, its a bit clumsy, but working.

**Comment by linux-china** [comment]
In your test code,  `describe` is a global function, and you should add `test: { globals: true},` according to https://vitest.dev/config/#globals    It's hard to let IDE to pare or execute all code to get Vitest configuration. 

Change your `vitest.config.js` as following: 

·```javascript
import {extractFromSvelteConfig} from 'vitest-svelte-kit'
import {defineConfig} from 'vitest/config'

export default defineConfig({
    ...extractFromSvelteConfig(),
    test: {
        globals: true,
    },
})
```

Reopen your project, and vitest test icons will be available as following: 

![image](https://user-images.githubusercontent.com/46711/180034765-2886ecf7-5a44-43f9-b6e0-3bdb648a7264.png)
