### ISSUE TITLE
Using configured nodejs interpreter

### ISSUE THREAD

**Issue by urkle** [linux-china/vitest-jetbrains-plugin#14]
This plugin uses the system node js interpreter and does not utilize the project-configured nodejs interpreter.  Thus, when my system is version 12 (other projects I work on demand it), vitest will not run as it requires at least 14 (which I have configured in my webstorm project configuration).

**Comment by linux-china** [comment]
Could you try this version?  If all good, and I will release a version.  

[vitest-jetbrains-plugin-0.4.1.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/9033672/vitest-jetbrains-plugin-0.4.1.zip)

**Comment by urkle** [comment]
@linux-china that appears to have worked for me.. (It ran using the configured node interpreter).
