### ISSUE TITLE
add `cts` and `mts` extensions

### ISSUE THREAD

**Issue by userquin** [linux-china/vitest-jetbrains-plugin#15]
We should add the `cts` and `mts` extensions, here the commit removing both extensions on my PR: https://github.com/linux-china/vitest-jetbrains-plugin/pull/4/commits/988b50f97e0c6cf17d63539e9ffe61f65be43850

It seems `Vite`  is adding them again, here the PR on `Vitest`: https://github.com/vitest-dev/vitest/pull/1540/files

**Comment by linux-china** [comment]
you can use Vitest Runner plugin to test xxx.test.mts or xxx.test.cts, and screenshot: 

![image](https://user-images.githubusercontent.com/46711/177014218-a6e9cce5-0742-4752-a09b-9d49afa8c061.png)

**Comment by userquin** [comment]
? the issue is about including the icons on the project structure

**Comment by linux-china** [comment]
My bad :)  Fixed already.
