### ISSUE TITLE
Yarn 3 no node_modules

### ISSUE THREAD

**Issue by ZiperRom1** [linux-china/vitest-jetbrains-plugin#18]
When using Yarn 3 package manager with PnP there is no `nodes_modules` so there is the following error when clicking the vitest icons in IDE

```
Error running 'vitest -t 'Top bar' src/components/__tests__/the-top-bar.spec.test.ts'

Cannot run program "node_modules/.bin/vitest" (in directory "/home/rom1/Projects/daia-ihm"): error=2, No such file or directory
```

**Comment by linux-china** [comment]
Fixed with 0.5.0 version.  Please add `"packageManager": "yarn@3.2.1"` to project's package.json.
