### ISSUE TITLE
Can't find tests with ' in their names

### ISSUE THREAD

**Issue by Acterion** [linux-china/vitest-jetbrains-plugin#19]
If I have a test case with name `prefixes strings that don't have the prefix yet` for example, and then click on run single test button on that test, vitest will quit with
``` 
filter:  have, the, prefix, yet packages/web-app/src/shared/helpers/routeHelper.test.ts
include: **/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**
watch exclude:  **/node_modules/**, **/dist/**

No test files found, exiting with code 1 
```
I assume ' symbol messes up command line arguments somewhere. Why are they not wrapped and is it possible to wrap them, so I don't have to change my test names?

**Comment by linux-china** [comment]
yes, please remove quotation mark from test name now.  I fixed it already and release new version soon.
