### ISSUE TITLE
No test files found

### ISSUE THREAD

**Issue by Mr-xzq** [linux-china/vitest-jetbrains-plugin#20]
## When add include, cause an exception to trigger:

```diff
export default defineConfig({
    test: {
+       // cause an exception to trigger
+       include: ['./playground/**/*.spec.[tj]s'],
        testTimeout: timeout,
        hookTimeout: timeout,
        globals: true,
        reporters: 'dot',
    },
    esbuild: {
        target: 'node14'
    }
})
```

## Error log:

```shell
npm exec -- vitest run -t test1 __tests__/auto-script-jsx.spec.js

 RUN  v0.18.1 E:/Desktop/Task/07-cdp-cfe/xzq-vite-plugins/playground/auto-script
-jsx

filter:  __tests__/auto-script-jsx.spec.js
include: ./playground/**/*.spec.[tj]s
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,out
put,temp}/**
watch exclude:  **/node_modules/**, **/dist/**

No test files found, exiting with code 1
```
## More info:
![image](https://user-images.githubusercontent.com/53166933/180602631-e291e2f3-085f-4f01-aaaa-812d4b7db26e.png)
![image](https://user-images.githubusercontent.com/53166933/180602680-0cd5f656-5e04-488a-8513-fe5f9fb4f885.png)
![image](https://user-images.githubusercontent.com/53166933/180602685-5b7bed64-377b-4c7b-99b0-3e3d4062557a.png)

**Comment by linux-china** [comment]
For Vitest Runner, the working directory is the package directory, and command line alike following: 

```
$ cd playground
$ npm exec -- vitest run -t test1 __tests__/auto-script-jsx.spec.js
```

It means different package could have different Vitest configuration because of npm workspaces.  You can move vitest.config.js to playground directory, and adjust the configuration and try again.

**Comment by Mr-xzq** [comment]
Thank you very much for your answer, this solved my problem.
