### ISSUE TITLE
Backticks used within `it()` throws an error while running single `it()`

### ISSUE THREAD

**Issue by pgejgalis-codilime** [linux-china/vitest-jetbrains-plugin#23]
Hello!
I see an error when I have backtics inside the `it()` section and I want to run just one test:

```typescript
  it('should allow to use backticks `here`', () => {
    // test code
  });
```

As a workaround I need to run whole `describe()` section (where I'm not using backticks)

```
npm exec -- vitest run -t "should allow to use backticks `here" src/my-test.tsx
sh: -c: line 0: unexpected EOF while looking for matching ``'
sh: -c: line 1: syntax error: unexpected end of file

Process finished with exit code 2.
```

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/61693448/183889299-73712419-30e5-457f-bf9b-6a2463692e2f.png">

**Comment by linux-china** [comment]
Yes, it's a bug from npm  https://github.com/npm/npm/issues/20644  

```
npm exec -- vitest run -t "should allow to use backticks `here`" src/my-test.tsx
```

and it works well with yarn.

```
yarn exec -- vitest run -t "should allow to use backticks \`here\`" tests/first.test.ts
```
