### ISSUE TITLE
Support for node v14

### ISSUE THREAD

**Issue by haassabine** [linux-china/vitest-jetbrains-plugin#26]
Hi,
is it possible to support node version 14.x as well with this plugin?
We would love to use this plugin, but cannot easily upgrade our node version yet.

The issue is currently, that your plugin runs the tests as:
`npm exec -- vitest run -t "Require Test" tests/unit/main.spec.ts`   
  
Which fails with under nodejs v.14:

> Usage: npm <command>
> where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami
> npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

The working version for node v.14 would be:
`npx vitest run -t "Require Test" tests/unit/main.spec.ts`

Can you please add support for this?

**Comment by linux-china** [comment]
Please config Node v14 as following and try new attached version. 

![image](https://user-images.githubusercontent.com/46711/185729099-c0703a7a-2c05-4198-af5f-e5709cfa50d8.png)


[vitest-jetbrains-plugin-0.6.3.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/9386240/vitest-jetbrains-plugin-0.6.3.zip)

**Comment by haassabine** [comment]
Works fine. Thank you
