### ISSUE TITLE
The "pnpm exec" command currently only works with the "-r" option

### ISSUE THREAD

**Issue by Djaler** [linux-china/vitest-jetbrains-plugin#27]
```
/usr/bin/pnpm exec -- vitest -t handleError src/foo.spec.ts
ERROR  The "pnpm exec" command currently only works with the "-r" option
```
Plugin version: 0.6.3
pnpm version: 5.18.10

**Comment by linux-china** [comment]
Could you upgrade your pnpm version?   If I append `-r` to pnpm 7, ad it does not work. 

![image](https://user-images.githubusercontent.com/46711/186214514-646c7a58-2d69-4d7b-b22e-7e50e868b144.png)

**Comment by Djaler** [comment]
Yes, with latest pnpm it works well
