### ISSUE TITLE
When test's description/single one contains `(/)` it is skipped, when `(/` it does not run

### ISSUE THREAD

**Issue by smolak** [linux-china/vitest-jetbrains-plugin#29]
**IMPORTANT**: It's only when I use the plugin and click on the icon to run the tests. When I run them in the terminal, all is fine.

---
### Skipping
I wanted to add some extra info in the description, e.g.:

```ts
describe('foo (bar / baz)', () => ...)
```

![Screenshot 2022-09-15 at 19 43 46](https://user-images.githubusercontent.com/1819138/190474019-f27632cc-be7c-43ff-9bd1-66d7e72b6a1d.png)

When I run it, the whole suite (and tests in it) are skipped.

### Not running

When if the description contains only `(/` it does not run.

![Screenshot 2022-09-15 at 19 43 56](https://user-images.githubusercontent.com/1819138/190474065-01dca6c4-739c-40a7-907b-b66bfd467758.png)

### Skipping

```ts
import { describe, it, expect } from 'vitest';

describe("Anything (/)", () => {
  it("should not be skipped", () => {
    expect(1).toEqual(2); // <-- it will not fail as the whole suit is skipped
  });
});

describe("It can have more text in it (like/this)", () => {
  it("should not be skipped", () => {
    expect(1).toEqual(2); // <-- it will not fail as the whole suit is skipped
  });
});
```

### Not running

```ts
import { describe, it, expect } from 'vitest';

describe("Anything (/", () => {
  it("should run this test", () => {
    expect(1).toEqual(2); // <-- it will not fail as the whole suit is not run
  });
});
```

**Comment by linux-china** [comment]
@smolak yes, it's a bug, and I should escape `(` and `)`  alike:  `npm exec -- vitest run -t "foo \(bar / baz1\)" tests/basic.test.ts`

It has been fixed on version 0.6.4, and I release it ASAP.
