### ISSUE TITLE
Monorepo issue with workspace directory

### ISSUE THREAD

**Issue by belgattitude** [linux-china/vitest-jetbrains-plugin#30]
Hey @linux-china 

First of all, a huge thank you for this marvelous plugin.

In monorepos the cli don't run in the workspace directory but in the root which creates some issues. It's stange because when looking at the code it should actually work: https://github.com/linux-china/vitest-jetbrains-plugin/blob/main/src/main/kotlin/com/github/linuxchina/jetbrains/plugins/vitest/VitestBaseRunLineMarkerProvider.kt#L62

I'm using latest PhpStorm 2022.2.1 with latest vitest plugin.

Tested on this repo: https://github.com/belgattitude/nextjs-monorepo-example.

```
.
├── apps
│   └── nextjs-app      
│       ├── next.config.mjs
│       ├── package.json        
│       ├── tsconfig.json      
│       └── vitest.config.ts   ## CONFIG FOR  NEXTJS_APP WORKSPACE
│
├── packages
│   ├── core-lib                 
│   │   ├── src/
│   │   ├── CHANGELOG.md
│   │   ├── package.json
│   │   └── tsconfig.json
│   │   └── vitest.config.json   ## CONFIG FOR  CORE_LIB WORKSPACE
│   └── ui-lib                 
├── .yarnrc.yml
└── package.json        
```

Is it an issue on your side too ?

PS: a picture 

![image](https://user-images.githubusercontent.com/259798/190927882-c5222c64-a419-49f4-9a23-dc70d9fae643.png)

When running the same command from the cli but in the workspace folder, it works

```
cd packages/core-lib/
/home/sebastien/.nvm/versions/node/v16.17.0/bin/yarn exec -- vitest -t usePromise packages/core-lib/src/hooks/__tests__/use-promise.test.tsx
```

**Comment by linux-china** [comment]
@belgattitude  yes, I think it's a bug, and now the working directory is project root for workspaces.  I adjusted working directory to package's directory. Could you try attached version?  Thanks. 

[vitest-jetbrains-plugin-0.6.4.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/9595847/vitest-jetbrains-plugin-0.6.4.zip)

**Comment by belgattitude** [comment]
Wow that was fast :smile: . It works perfectly, thanks for for quick support.

**Comment by windylaugit** [comment]
> @belgattitude yes, I think it's a bug, and now the working directory is project root for workspaces. I adjusted working directory to package's directory. Could you try attached version? Thanks.
> 
> [vitest-jetbrains-plugin-0.6.4.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/9595847/vitest-jetbrains-plugin-0.6.4.zip)

cant't find this version(0.6.4) in market?

**Comment by windylaugit** [comment]
> @belgattitude yes, I think it's a bug, and now the working directory is project root for workspaces. I adjusted working directory to package's directory. Could you try attached version? Thanks.
> 
> [vitest-jetbrains-plugin-0.6.4.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/9595847/vitest-jetbrains-plugin-0.6.4.zip)

I can't find the version(0.6.4) in the market. And the zip package does not support webstorm version: 2021.2.2

**Comment by linux-china** [comment]
@windylaugit   Compatibility range of  version 0.6.4 is  2021.3 — 2022.2.2 and 2021.2 is not compatible.

**Comment by windylaugit** [comment]
> @windylaugit Compatibility range of version 0.6.4 is 2021.3 — 2022.2.2 and 2021.2 is not compatible.

Ok，I got it! Thinks!
