### ISSUE TITLE
Add support for PhpStorm 2023.1

### ISSUE THREAD

**Issue by MrKoopie** [linux-china/vitest-jetbrains-plugin#40]
In PhpStorm 2023.1 I get an incompatibility warning:
`Incompatible: requires IDE build 223.* or earlier`

Can you add support for 2023.1?

**Comment by dennyweiss** [comment]
I'm wondering and this is not the only plugin that has to fight with this issue. What has a plugin author to change every time to stay compatible with the IDE?
