### ISSUE TITLE
Does not support subproject independent installing `vitest`

### ISSUE THREAD

**Issue by iamanewofkotlin** [linux-china/vitest-jetbrains-plugin#5]
there is error below.
```
Error running 'vitest run -t 'foo' packages/bar/test/codegen.spec.ts': Cannot run program "node_modules/.bin/vitest" (in directory error=2, No such file or director
```

**Comment by linux-china** [comment]
Could you try this version?  If all is good and I will release a new version.   
[vitest-jetbrains-plugin-0.2.2.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/8405517/vitest-jetbrains-plugin-0.2.2.zip)

**Comment by iamanewofkotlin** [comment]
@linux-china Not work. And the `click icon` disappeared when using the new install file.

**Comment by linux-china** [comment]
@iamanewofkotlin  could you share a project on github?

**Comment by iamanewofkotlin** [comment]
@iamanewofkotlin I am sorry for this, I can not. It is a `monorepo`. Just like [vueuse](https://github.com/vueuse/vueuse).
But i installing the ``vites`` in ``packages/foo`` dir that is a subproject. 
Could you understanding my mean

**Comment by linux-china** [comment]
Some weird, and it works well on webstorm. 

![image](https://user-images.githubusercontent.com/46711/161879069-0ffab30a-b221-45be-b819-93ea42bde560.png)


could you install this version to test again? 
[vitest-jetbrains-plugin-0.2.2.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/8422907/vitest-jetbrains-plugin-0.2.2.zip)

**Comment by linux-china** [comment]
Now the plugin does not support Vitest with tsconfig.json, and you should use `import { assert, expect, test } from 'vitest'`. 

```
// tsconfig.json
{
  "compilerOptions": {
    "types": ["vitest/globals"]
  }
}
```

**Comment by iamanewofkotlin** [comment]
@linux-china Pardon. Maybe restarting my webstorm or reinstalling ``vitest`` to my monorepo root dir can resolve the issue. Thanks for your replying.

I will move ``vitest`` to my monorepo root dir.

**Comment by linux-china** [comment]
>>   the click icon disappeared when using the new install file.

You are using Windows?  Adjust logic for Windows path match.   Please install new version and restart WebStorm and try it again. 

[vitest-jetbrains-plugin-0.2.2.zip](https://github.com/linux-china/vitest-jetbrains-plugin/files/8423025/vitest-jetbrains-plugin-0.2.2.zip)

**Comment by iamanewofkotlin** [comment]
@linux-china My computer is mac, Macos version is ``11.5 `` and webstorm version is ``2021.3.3``. 
I can not testing your updates that is for ``windows``. Sorry

**Comment by linux-china** [comment]
:)  My laptop is Mac too, and it should work.  Ignore that because some developers have reported Windows problem.

**Comment by iamanewofkotlin** [comment]
> :) My laptop is Mac too, and it should work. Ignore that because some developers have reported Windows problem.

Thanks for your generous contributes for open-source.

**Comment by linux-china** [comment]
It works now?  I opened vitest repository, and it works well with examples sub projects.   

![image](https://user-images.githubusercontent.com/46711/161885937-8e859474-a439-459a-9b59-5beeaa797a5c.png)

**Comment by iamanewofkotlin** [comment]
@linux-china Take some time. I need adjust my project. I will reply to you ASAP. Pardon, sir.

**Comment by iamanewofkotlin** [comment]
@linux-china It's work for me! But when invoked in the way i clicking ``describe`` beside icon. It will throw error ``document is not defined``. Becase the one ``test`` of ``describe`` is ``vue setup`` environment

```text
  × packages/vue/test/fields.spec.ts > foo > bar
   → document is not defined
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  packages/vue/test/fields.spec.ts > foo > bar

ReferenceError: document is not defined
 ❯ Proxy.mount node_modules/.pnpm/registry.npmmirror.com+@vue+test-utils@2.0.0-rc.17_vue@3.2.31/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7757:14
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

    7755|     addToDoNotStubComponents(component);
    7756|     registerStub(originalComponent, component);
    7757|     var el = document.createElement('div');
       |              ^
    7758|     if (options === null || options === void 0 ? void 0 : options.atta…
    7759|         var to = void 0;
 ❯ packages/vue/test/fields.spec.ts:42:4

Test Files  1 failed (1)
     Tests  1 failed (1)
      Time  7.03s (in thread 22ms, 32020.24%)

```

It is test code. may can help for you.

```ts
import { describe, test } from 'vitest';
import { mount } from '@vue/test-utils';
import { defineComponent } from 'vue';

describe('foo', () => {
  test('bar', () => {
    const props = {
      foo: 1
    };

    const foobar = defineComponent({
      name: 'FooBar',
      template: `<div>abc</div>`
    });

    const Root = {
      components: {
        FooBar: foobar
      },
      template: `<foo-bar />`,
      setup() {}
    };

    mount(Root);
  });
});

```

**Comment by iamanewofkotlin** [comment]
@linux-china and i do not know why the test file had generate two file ``foo.spec.js`` and ``foo.spec.js.map`` in same dir.

**Comment by userquin** [comment]
@linux-china 

FYI: I have this repo with only the vitest core tests you can use to test the plugin (not yet updated to latest): https://github.com/userquin/vitejs-vite-latest 

I will check if your latest changes supporting monorepo with vitest itself is working on windows (with previous version not working).
