### ISSUE TITLE
Not showing up in IntelliJ

### ISSUE THREAD

**Issue by smeevil** [linux-china/vitest-jetbrains-plugin#6]
Hi,

I just installed the plugin in IntelliJ-Ultimate 2021.3.3 and restarted the idea.
I open up a `index.test.tsx` or `index.spec.tsx` but I only see the cypress and jest options to run the test.
The icons as shown in the screenshot do not present themselves, and the run configuration does not show an entry for vitest either. I've tried both version 0.2.1 and 0.2.2 of the plugin.

Am I maybe missing a configuration step?

Gerard.

**Comment by linux-china** [comment]
Now the plugin does not support Vitest with tsconfig.json, and you should use import { assert, expect, test } from 'vitest'.


![image](https://user-images.githubusercontent.com/46711/162799913-45f6888f-a25f-4b9d-a37f-3af4f5278529.png)

**Comment by smeevil** [comment]
Hi,

Thanks for the quick reply :)
Adding the import does indeed enable the plugin.

When trying to run it, it bails with the following though:

```
/bin/zsh --login -c "node_modules/.bin/vitest run -t \"should pass given className and fallback without logo\" src/Components/BrandLogo/index.spec.tsx"
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /Users/ciaccount/actions-runner/_work/macos/macos/rust-lib/alacritty_terminal/src/grid/mod.rs:452:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by linux-china** [comment]
@smeevil  could you run the test from command line?    If possible, could you open the project by WebStorm command line by `webstorm .` and try it again?  I have no idea about this problem.  :)

**Comment by linux-china** [comment]
Fixed. New version uses `npm exec -- vitest` to run test.
