### ISSUE TITLE
support vitest globals

### ISSUE THREAD

**Issue by hcg1023** [linux-china/vitest-jetbrains-plugin#7]
We want to be able to support the way vitest is introduced globally
希望支持全局vitest的方式

vite.config.ts
```ts
/// <reference types="vitest" />
/// <reference types="vitest/globals" />
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [vue()],
	test: {
		environment: 'jsdom',
		globals: true,
	},
})
```

**Comment by linux-china** [comment]
这个可以支持的，不复杂，但是不能每次都去检测vite.confg.ts文件，所以有一个缓存的机制，这个我看一下Open API。

**Comment by hcg1023** [comment]
> 这个可以支持的，不复杂。 考虑到缓存机制，如果你第一次添加 Vitest globals，你需要重新打开项目一次，主要是不想缓存复杂化。 请安装最新的0.2.3版本 https://github.com/linux-china/vitest-jetbrains-plugin/releases/tag/v0.2.3
> 
> ![image](https://user-images.githubusercontent.com/46711/163043786-5b4622ad-988b-4e0e-83cc-e38ab87372b4.png)

非常nice，大佬牛啊
