### ISSUE TITLE
Not working with WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by SirMishaa** [linux-china/vitest-jetbrains-plugin#8]
Hello 

It looks like it doesn't work with [WSL](https://docs.microsoft.com/en-us/windows/wsl/about). I got the following error message: 
> Cannot run program "\\wsl$\Ubuntu\home\mishaa\dev\deepvue\node_modules\.bin\vitest.CMD" (in directory "\\wsl$\Ubuntu\home\mishaa\dev\deepvue"): CreateProcess error=2, Le fichier spécifié est introuvable

I'm using this template : https://github.com/antfu/vitesse-lite for Vue 3 and Vitest test framework. It's working good with CLI. 
I'm under the last version of PHPStorm. Same error with Webstorm. 

The basic tere is here : 
```ts
import { describe, expect, it } from 'vitest'

describe('Hi', () => {
  it('should works', () => {
    expect(1 + 1).toEqual(2)
  })
})
```

![image](https://user-images.githubusercontent.com/42717232/164953164-05ede828-9fa0-4881-8816-b294c1f3da40.png)

![image](https://user-images.githubusercontent.com/42717232/164953186-05806470-cc30-4919-81ed-3cff72e82572.png)

![image](https://user-images.githubusercontent.com/42717232/164953199-342c9507-fee8-41e6-b3ba-b60aae6adb4a.png)

**Comment by SirMishaa** [comment]
And yes, of course, the file is here. 
It looks like the plugin try to open the file in a "windows way". 

![image](https://user-images.githubusercontent.com/42717232/164953238-91cccd10-a62c-4824-a7c7-d460fb91f6e3.png)

**Comment by linux-china** [comment]
>> It looks like the plugin try to open the file in a "windows way".

I will take a look.  I have no idea about WSL, and I should treat it as Linux? 

```
 val (binDir, command) = if (SystemInfo.isWindows) {
            "${workDir.path.replace('/', '\\')}\\${nodeBinDir.replace('/', '\\')}" to "vitest.CMD"
        } else {
            nodeBinDir to "vitest"
        }
```

**Comment by SirMishaa** [comment]
Same error: 
![image](https://user-images.githubusercontent.com/42717232/166096422-d948d669-5ea0-434d-9793-da3904e4bb53.png)

**Comment by linux-china** [comment]
@SirMishaa  could you post your command line to run test  in WSL? thanks.

**Comment by linux-china** [comment]
Now use `npm exec -- vitest ` to run test, and OS detection not required.   Please try new 0.5.0 version.
