### ISSUE TITLE
Any idea how to run tests in debug mode using this plugin?

### ISSUE THREAD

**Issue by eswann** [linux-china/vitest-jetbrains-plugin#9]
First, thanks so much for the plugin...do you know how it could be tweaked to run the tests in debug mode?

Thanks!

**Comment by linux-china** [comment]
This plugin just a temp solution before official Vitest support from WebStorm. I think JetBrains people will do this job, and they know Vitest is great framework. For Vitest support in WebStorm, please vote here: https://youtrack.jetbrains.com/issue/WEB-54437

I don't want to waste lots of time on temporary plugin, and JetBrains team will take over this job :)
